name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        stack-version: '2.1.3'
    - name: Install dependencies
      run: |
        echo 'stack setup'
    - name: Build
      run: |
        stack build
    - name: Run tests
      run: stack test
